version: "3.9"
services:
  db:
    image: postgres:alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=conferencedb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  service:
    build: .
    entrypoint: ["./gradlew", "bootRun"]
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/conferencedb
    depends_on:
      - db

